/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        System.out.println(new App());


       Scanner sc = new Scanner(System.in);
        Conversor cv = new Conversor();

        System.out.println("Escolha uma opção: \n" +
                            "1- Celsius para Fahrenheit;\n" +
                            "2- Fahrenheit para Celsius.");

        int entrada = sc.nextInt();

        System.out.println("Insira a temperatura a ser convertida: ");
        int temp = sc.nextInt();

        switch (entrada) {
            case 1:
                System.out.println("Fahrenheit: " + cv.toFahrenheit(temp));
                break;
            case 2:
                System.out.println("Celsius: " + cv.toCelsius(temp));
                break;
            default:
                throw new IllegalArgumentException("aaaaaaaaaaaaaaaa");
        }

        sc.close();
    }
}
